name: Build & Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
env:
  # Stop wasting time caching packages / Disable sending usage data to Microsoft
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
      - name: Restore
        working-directory: ./src  
        run: dotnet restore
      - name: Build
        working-directory: ./src
        run: dotnet build --no-restore
  test:
    needs: build
    runs-on: ubuntu-latest
    env:
#      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
#      AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
      ASPNETCORE_ENVIRONMENT: 'Workflow'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
      - name: Test
        working-directory: ./src
        run: dotnet test --verbosity normal